sudo: false
language: go
go:
  - 1.4.2
  - tip
notifications:
  irc: 
    channels: "chat.freenode.net#seedstack-dev"
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    skip_join: true
    use_notice: true
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install: go get gopkg.in/yaml.v2
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - go test -cover ./seed
  - go build ./seed
